### ISSUE TITLE
PubmedItem in wdi_helpers.py doesn't work for some items in PMC

### ISSUE THREAD

**Issue by tarrow** [SuLab/WikidataIntegrator#10]
It seems that at least for some items the query string used to get metadata from EuropePMC is malformed for content in PubMedCentral.

For example if you init with:
`wdi_helpers.PubmedItem('PMC3139704', id_type='PMC')`

Then the query string to the EBI appears to be: `http://www.ebi.ac.uk/europepmc/webservices/rest/search?query=EXT_ID:PMC3139704%20AND%20SRC:PMC&resulttype=core&format=json`

This returns no results.

I think the correct string should be like: `http://www.ebi.ac.uk/europepmc/webservices/rest/search?query=PMCID:PMC3139704&resulttype=core&format=json`

Something similar has already been done for DOI. I guess this may need to be done for the other identifiers in PubmedItem.id_types.

I think EXT_ID and SRC may only hold one value corresponding to whichever database EuropePMC got the metadata from first. This means that if you don't search by an item's 'main' id then you get no results.

**Comment by tarrow** [comment]
Don't suppose you'd be able to bump the version and push it to pypy if you
have a a moment?

**Comment by stuppie** [comment]
Done
