### ISSUE TITLE
Pandas required but not installed by pip install

### ISSUE THREAD

**Issue by boxed** [SuLab/WikidataIntegrator#101]
Also, is pandas really required? Seems a bit excessive to get all of pandas and numpy for basic wikidata access. Just importing * from wdi_core takes forever.

**Comment by andrawaag** [comment]
Can you elaborate a bit? What steps did you take and in what version of pip install? In the current requirements file pandas is listed: https://github.com/SuLab/WikidataIntegrator/blob/master/requirements.txt. Pandas does get installed in our bot workflows. wrt basic wikidata access it might indeed be a bit excessive, however pandas is used to process for example sparql results from the wikidata query service. If however this is causing slow response in basic scenario's I am happy to review a more slim approach. i.e. moving those function to a designated module.

**Comment by boxed** [comment]
You can just move the import inside the function that needs it.

**Comment by boxed** [comment]
As for pandas: https://github.com/SuLab/WikidataIntegrator/blob/master/setup.py#L34

The normal way to do setup.py is to read requirements.txt and insert its contents there.
