### ISSUE TITLE
Allow modification of sleep time in write calls

### ISSUE THREAD

**Issue by alejgh** [SuLab/WikidataIntegrator#139]
Hello, we are currently working in a synchronization system between RDF files and a Wikibase instance, and have been using WikidataIntegrator to do so. First of all, thank you a lot for the tool, it has been really useful and nice to use for us :)

We have done some benchmarks in the last days, were we noticed that most of the time (~60%) in the synchronisation is spent on sleep calls from wdi_core.

<img width="1233" alt="benchmarks_synchronization" src="https://user-images.githubusercontent.com/29005950/84012196-79546d80-a977-11ea-8cec-b1c0dbec907e.png">

They are coming from the following line in the write method from the WDItemEngine class:
```python
def write(self, login, bot_account=True, edit_summary=‘’, entity_type=‘item’, property_datatype=‘string’, max_retries=1000, retry_after=60):
	…
	time.sleep(.5)
	return self.wd_item_id
```

Is this sleep used specifically to slow the number of writes to the Wikidata API, or is it also needed to write data to a custom Wikibase instance?

If this is not needed, I would like to explore some options to modify the sleep time. This would greatly improve the performance when writing data to a custom Wikibase instance.

A simple approach would be to add the sleep time as an additional parameter, with the default value of .5, and document its purpose in the method docstrings.
```python
def write(…, write_delay=.5):
```

**Comment by andrawaag** [comment]
Yes, this is indeed provided to slow down the writes to the Wikidata API, but it stems from before the current issues with the throttling measures and the max-lag. So now might be the best time to review whether or not we still want to do maintain this. 
So yes you are welcome to explore other options. I will do the same.

**Comment by alejgh** [comment]
Yes, I would be glad to explore other solutions. Could you mind explaining what some of those issues are? I have been looking at the wdi_core writing code, and it is already taking into account the max-lag parameter. I though that respecting it was already enough as a throttling measure to develop Wikidata bots.
