### ISSUE TITLE
Add PMCID statement from helper scripts

### ISSUE THREAD

**Issue by tarrow** [SuLab/WikidataIntegrator#14]
Currently the PMCID help script doesn't add a PMCID statement to the item.

It probably should.

Similarly the when invoked as a PMID it should also do this *if* there is one.

**Comment by Daniel-Mietchen** [comment]
Example from the duplicate that I just closed: 
I started
https://www.wikidata.org/w/index.php?title=Q30729891&oldid=507209321
by way of
https://tools.wmflabs.org/fatameh/pmc/add/PMC95859
but the item does not have a PMCID statement.

**Comment by stuppie** [comment]
https://github.com/SuLab/WikidataIntegrator/commit/0b84c12f0e493823e0269251f46b30dec5e039ac

**Comment by Daniel-Mietchen** [comment]
This is still not working:
I just started
https://www.wikidata.org/wiki/Q31704640
by way of 
https://tools.wmflabs.org/fatameh/pmc/add/PMC5469494
but this did not create a PMCID statement.

**Comment by Daniel-Mietchen** [comment]
It seems to work now: I just created 
https://www.wikidata.org/wiki/Q31877629
by way of
https://tools.wmflabs.org/fatameh/pmc/add/PMC5088373 ,
and the item was indeed started with the correct PMCID statement.
