### ISSUE TITLE
Suggestions for restructuring WDI 

### ISSUE THREAD

**Issue by despens** [SuLab/WikidataIntegrator#158]
WDI currently treats most actions idependently, with the default that everything would happen on Wikidata.

The no-hierachy approach is causing several things need to be declared multiple times, and interaction in between different Wikibase instances is complicated. It is also confusing compared with other API wrappers that express hierarchy.

I would want to suggest that every function and data structure should be a child of a Wikibase instance.

```py
my_wikibase = wdi.Wikibase(mediawiki_api_url='https://...',
                           sparql_endpoint_url='https://...',
                           mediawiki_user='alice bobbinsdottir',
                           mediawiki_passwort='passw0rd')
```

**Any `Wikibase` instance is treated as a Mediawiki + SPARQL endpoint.**

Login and password would be optional, in that case only reading functionality would be usable. 

Any other definitions that might be required would also be added here, for instance any special properties (such as `instance of`, `same as` etc, if that is benefitial).

If some information is not given, Wikidata defaults are assumed.

Items and properties can only be used in the context of a Wikibase instance:

```py
item = my_wikibase.Item('Q7173')  # existing item

item.statements['P5']
# → [<wdi.Statement>, <wdi.Statement>]

# item manipulation
for statement in item.statements['P5']:
    if statement.value == 'wrong value':
        statement.delete()

new_statement = my_wikibase.Statement('P5', 'good value', qualifiers=[])
item.statements.append(new_statement)
item.write()

new_description = {'en': 'very cool item',
                   'fr': 'une chose très cool'}
new_statements = [{'P1': [item]}]
new_item = my_wikibase(data={statements=[new_statement],
                             description=new_description)

new_item.write()
```

Mappings in between two Wikibases could be defined to allow matching and augmenting data:

```py
my_wikibase.properties['P5'].match(wikidata.properties['P139'])
my_wikibase.properties['P9'].match(wikidata.properties['P67'])

new_item = my_wikibase.Item(wikidata.items['Q9143'])
new_item.write()

my_wikibase.items['Q281'].augment(wikidata.itmes['Q519873'])
```

**Comment by andrawaag** [comment]
I really like the idea and we might consider it a proper candidate for version 1.0.0. 

However, at the same time, I would like to progress with caution. Quite some bots currently rely on the current structure and before moving forward I need to assess how any change effects all running bots. 

However, I created [this branch](https://github.com/SuLab/WikidataIntegrator/tree/restructuring-WDI) where we could explore and  test this restructuring on.
