### ISSUE TITLE
Can't set a required function for PyShExC in Wikidata integrator. 

### ISSUE THREAD

**Issue by andrawaag** [SuLab/WikidataIntegrator#163]
Currently, various ShEx functions are part of the WDI library. It builds on top of the [https://github.com/hsolbrig/PyShEx PyShEx] library. 
Currently importing PyShEx is unsuccessful. I tried to set an earlier version number, but the issue seems to be that PyShEx in its turn needs a specific version of PyShExc:

`ERROR: Could not find a version that satisfies the requirement pyshexc==0.8.3 (from pyshex->wikidataintegrator) (from versions: 0.2.1, 0.3.0, 0.3.2, 0.3.4, 0.4.1, 0.4.2, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.6.1, 0.7.0)
ERROR: No matching distribution found for pyshexc==0.8.3 (from pyshex->wikidataintegrator)`

**Comment by NoahFinberg** [comment]
Any update here? I've recently started having this issue even though I had this running successfully before..

**Comment by NoahFinberg** [comment]
Ok so issue for me ended up being that I was using an outdated version of pip. Trying running `pip install --upgrade pip` and then rerun `pip install wikidataintegrator`. I had recently reinstalled python on my machine and began using https://github.com/pyenv/pyenv-virtualenv for virtual env management. For context, I'm running python 3.6.5.

**Comment by andrawaag** [comment]
PyShEx and some libraries are compatible with python 3.7+ As a result WDI raizes issues with python 3.6.x. The solution is to upgrade to python 3.7+.
