### ISSUE TITLE
Is using it on other instances of Wikibase supported?

### ISSUE THREAD

**Issue by matkoniecz** [SuLab/WikidataIntegrator#164]
For example at OSM Wiki - https://wiki.openstreetmap.org/wiki/Item:Q4716 (note https://phabricator.wikimedia.org/T269635 - not sure where is the problem)

I see #55 #113 indicating that it is at least desirable and that some issues were fixed.

I see  #150 but I am not sure is it an annoyance or a critical blocker.

**Comment by LeMyst** [comment]
Yeah, main functions in WikidataIntegrator works with Wikibase, you can use it.

**Comment by LeMyst** [comment]
Yeah, WikidataIntegrator work with the "Item:" and "Property:" namespaces.

In the phabricator ticket you referenced, there is a misunderstanding between the Main namespace (where "Key:amenity" is) and the Item namespace (where you have "Q4716")

**Comment by matkoniecz** [comment]
Thanks for a reply!
