### ISSUE TITLE
add method to create a triple in a Wikibase instance

### ISSUE THREAD

**Issue by kodymoodley** [SuLab/WikidataIntegrator#177]
I cannot see in the documentation how to create a triple e.g. `Q6 P4 Q9` in a non-Wikidata Wikibase instance (where `Q6`, `P4` and `Q9` all exist in the instance).

When sending a request like this on a local Wikibase instance:

`{'action': 'wbcreateclaim', 'entity': 'Q295', 'snaktype': 'value', 'property': 'P108', 'value': '{"entity-type":"item","numeric-id":78}', 'token': '...', 'format': 'json'}`

I get this error:

`{'error': {'code': 'invalid-snak', 'info': 'Invalid snak data.', 'messages': [{'name': 'wikibase-api-invalid-snak', 'parameters': [], 'html': {'*': 'Invalid snak data.'}}], '*': 'See http://.../w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.'}}`

**Comment by andrawaag** [comment]
Can you try the following code:
`
wbstack = "<Add you wbstack instance>"
wikibase = "https://{}.wiki.opencura.com/".format(wbstack)
api = "https://{}.wiki.opencura.com/w/api.php".format(wbstack)
sparql = "https://{}.wiki.opencura.com/query/sparql".format(wbstack)
entityUri = wikibase.replace("https:", "http:")+"entity/"

WBUSER = "<username>"
WBPASS = "<password>"
login = wdi_login.WDLogin(WBUSER, WBPASS, mediawiki_api_url=api)
localEntityEngine = wdi_core.WDItemEngine.wikibase_item_engine_factory(api,sparql)
statements = []
statements.append(wdi_core.WDItemID(value="Q9"], prop_nr="P4")
item = localEntityEngine(wd_item_id="Q6", data=statements)
item.write(login)
`

You need to provide your wikibase server details plus username/password at the places between <>. 
This code works on an instance of wbstack.com. For individual wikibases you need to provide the API and sparql variables accordingly.

**Comment by kodymoodley** [comment]
> Can you try the following code:
> `
> wbstack = ""
> wikibase = "https://{}.wiki.opencura.com/".format(wbstack)
> api = "https://{}.wiki.opencura.com/w/api.php".format(wbstack)
> sparql = "https://{}.wiki.opencura.com/query/sparql".format(wbstack)
> entityUri = wikibase.replace("https:", "http:")+"entity/"
> 
> WBUSER = ""
> WBPASS = ""
> login = wdi_login.WDLogin(WBUSER, WBPASS, mediawiki_api_url=api)
> localEntityEngine = wdi_core.WDItemEngine.wikibase_item_engine_factory(api,sparql)
> statements = []
> statements.append(wdi_core.WDItemID(value="Q9"], prop_nr="P4")
> item = localEntityEngine(wd_item_id="Q6", data=statements)
> item.write(login)
> `
> 
> You need to provide your wikibase server details plus username/password at the places between <>.
> This code works on an instance of wbstack.com. For individual wikibases you need to provide the API and sparql variables accordingly.

Thanks, I tried this code:

```
wikibase = "http://my-wikibase-instance.org/"
api = "http://my-wikibase-instance.org/w/api.php"
sparql = "http://my-wikibase-instance.org/bigdata/namespace/wdq/sparql"
entityUri = wikibase.replace("https:", "http:")+"entity/"

WBUSER = ""
WBPASS = ""
login = wdi_login.WDLogin(WBUSER, WBPASS, mediawiki_api_url=api)
localEntityEngine = wdi_core.WDItemEngine.wikibase_item_engine_factory(api,sparql)
statements = []
statements.append(wdi_core.WDItemID(value="Q295", prop_nr="P108"))
item = localEntityEngine(wd_item_id="Q6", data=statements)
item.write(login)
```
and now I get this error:

```
---------------------------------------------------------------------------
WDApiError                                Traceback (most recent call last)
/tmp/ipykernel_1411/4092155577.py in <module>
     11 statements.append(wdi_core.WDItemID(value="Q295", prop_nr="P108"))
     12 item = localEntityEngine(wd_item_id="Q6", data=statements)
---> 13 item.write(login)

/opt/conda/lib/python3.9/site-packages/wikidataintegrator-0.8.21-py3.9.egg/wikidataintegrator/wdi_core.py in write(self, login, bot_account, edit_summary, entity_type, property_datatype, max_retries, retry_after)
   1319                     raise NonUniqueLabelDescriptionPairError(json_data)
   1320                 else:
-> 1321                     raise WDApiError(json_data)
   1322             elif 'error' in json_data.keys():
   1323                 raise WDApiError(json_data)

WDApiError: {'error': {'code': 'modification-failed', 'info': 'Bad value type wikibase-entityid, expected string', 'messages': [{'name': 'wikibase-validator-bad-value-type', 'parameters': ['wikibase-entityid', 'string'], 'html': {'*': 'Bad value type wikibase-entityid, expected string'}}], '*': 'See http://eu-corporate-mobility.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.'}}
```

**Comment by andrawaag** [comment]
P108 is expecting a string value and not a Wikibase Item ID. 
To fix this, you either need to delete P108 and create a property with the same semantics and then select "wikibase-item" as type (or "item"). Or if P108 needs to remain a property with a value type of String, the following line needs to be added in stead of the one above:

statements.append(wdi_core.WDString(value="Some string value", prop_nr="P108"))

**Comment by kodymoodley** [comment]
> P108 is expecting a string value and not a Wikibase Item ID.
> To fix this, you either need to delete P108 and create a property with the same semantics and then select "wikibase-item" as type (or "item"). Or if P108 needs to remain a property with a value type of String, the following line needs to be added in stead of the one above:
> 
> statements.append(wdi_core.WDString(value="Some string value", prop_nr="P108"))

This was indeed the issue, creating a property with the right domain / datatype ("wikibase-item") solves it! Thank you very much @andrawaag !
