### ISSUE TITLE
Unable to handle errors from WDFunctionsEngine.execute_sparql_query

### ISSUE THREAD

**Issue by andrewtavis** [SuLab/WikidataIntegrator#189]
Hello :) 

I'm trying to use WikidataIntegrator to update a series of Wikidata generated JSONs that I have in the app [Scribe - Language Keyboards](https://github.com/scribe-org/Scribe-iOS). Scribe has tons of `.sparql` files that to now need to be ran independently, and I'm working on [an issue](https://github.com/scribe-org/Scribe-iOS/issues/95) where all of these will be ran by a single Python file. 

Looking at [wdi_core.py](https://github.com/SuLab/WikidataIntegrator/blob/13e21e723f2607c4f42c6bab2d7078eebd9ec62c/wikidataintegrator/wdi_core.py), I don't see how I'm able to pass over unsuccessful queries and move onto the next ones. `response.raise_for_status()` in [execute_sparql_query](https://github.com/SuLab/WikidataIntegrator/blob/13e21e723f2607c4f42c6bab2d7078eebd9ec62c/wikidataintegrator/wdi_core.py#L85) at times returns an error, and in these cases there doesn't seem to be a returned value via `results = response.json()` that I could then use as a trigger to skip the operation.

If returning `None` or some other response would be acceptable to you all in these cases, I'd be happy to write a PR to do this. Any other suggestions would also be very appreciated :)

Thanks for your time!

**Comment by LeMyst** [comment]
Hello @andrewtavis 

Do you have some code example? Because I think you can try/catch the exception raised by raise_for_status()

**Comment by andrewtavis** [comment]
Hello @LeMyst, thanks for the reply :)

Here's the part of [Scribe-iOS/Data/update_data.py](https://github.com/scribe-org/Scribe-iOS/blob/main/Data/update_data.py) where I'm using `execute_sparql_query`:

```python
with open(query_path) as file:  # query_path leads to a .sparql file
    query_lines = file.readlines()

query = wdi_core.WDFunctionsEngine.execute_sparql_query(
    """{}""".format("".join(query_lines))
)

query_results = query["results"]["bindings"]  # being a dict if working
```

Maybe a try/catch on the part where I'm running the query? I'm just not sure how to go about dealing with a lack of returned result from `execute_sparql_query`.

Thanks again :)

**Comment by andrewtavis** [comment]
I guess that I could try/catch `response.raise_for_status()` in a fork of WikidataIntegrator for my own purposes, but then this might be awkward later on when hopefully others will be contributing and adding data to Scribe (one can hope 😊 ).

**Comment by LeMyst** [comment]
A missing thing in your code is the lack of test if `query` is None (occur when the max_tries is reached).
You can go outside your for-loop when the exception occur.

```python
with open(query_path) as file:  # query_path leads to a .sparql file
    query_lines = file.readlines()

try:
    query = wdi_core.WDFunctionsEngine.execute_sparql_query("".join(query_lines))
except HTTPError as err:
    print(f'HTTPError with {query_name}: {err}')
    continue

if query:
    query_results = query["results"]["bindings"]  # being a dict if working
    ...
else:
    print(f'Nothing returned by the SPARQL server for {query_name}')
```

Can you give the the HTTP error code you have with the raise_for_status() ? I think WikidataIntegrator miss some frequent code, and should have something like this instead of just 503:
`if response.status_code in (500, 502, 503, 504):`

I hope I correctly understood your issue.

**Comment by andrewtavis** [comment]
Thanks for your further help!

Issue was that the SPARQL itself was malformed (apologies for not checking for rigorously), but then in this case `except HTTPError as err:` did not trigger and the function still hung without a result. The SPAQRL was wrong as I was filtering based on a variable I'd renamed, but not in the filter itself. The WDQS result from this is `Query timeout limit reached`. Explicitly:

- Say you have [this query of Swedish nouns and pronouns](https://query.wikidata.org/#%23%20All%20Swedish%20%28Q9027%29%20nouns%20with%20their%20plural%2C%20gender%20and%20genitive%20forms.%0A%23%20Enter%20this%20query%20at%20https%3A%2F%2Fquery.wikidata.org%2F.%0A%0A%23%20Note%3A%20does%20not%20include%20pronouns%20as%20the%20query%20wasn%27t%20running.%0A%0ASELECT%20DISTINCT%20%3FnominativeSingular%20%3FnominativePlural%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3FgenitiveSingular%20%3FgenitivePlural%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Fgender%20WHERE%20%7B%0A%0A%20%20%23%20Nouns%20and%20pronouns.%0A%20%20VALUES%20%3FnounTypes%20%7B%20wd%3AQ1084%20wd%3AQ147276%20%7D%0A%20%20%3Flexeme%20a%20ontolex%3ALexicalEntry%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20dct%3Alanguage%20wd%3AQ9027%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AlexicalCategory%20%3Fnoun%20.%0A%20%20FILTER%28%3Fnoun%20%3D%20%3FnounTypes%29%0A%0A%20%20%23%20Indefinite%20forms%20in%20both%20nominative%20and%20genitive.%0A%20%20OPTIONAL%20%7B%0A%20%20%20%20%23%20Nominative%20Singular%0A%20%20%20%20%3Flexeme%20ontolex%3AlexicalForm%20%3FnominativeSingularForm%20.%0A%20%20%20%20%3FnominativeSingularForm%20ontolex%3Arepresentation%20%3FnominativeSingular%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgrammaticalFeature%20wd%3AQ53997857%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgrammaticalFeature%20wd%3AQ131105%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgrammaticalFeature%20wd%3AQ110786%20.%0A%0A%20%20%20%20%23%20Nominative%20Plural%0A%20%20%20%20%3Flexeme%20ontolex%3AlexicalForm%20%3FnominativePluralForm%20.%0A%20%20%20%20%3FnominativePluralForm%20ontolex%3Arepresentation%20%3FnominativePlural%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgrammaticalFeature%20wd%3AQ53997857%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgrammaticalFeature%20wd%3AQ131105%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgrammaticalFeature%20wd%3AQ146786%20.%0A%0A%20%20%20%20%23%20Genitive%20Singular%0A%20%20%20%20%3Flexeme%20ontolex%3AlexicalForm%20%3FgenitiveSingularForm%20.%0A%20%20%20%20%3FgenitiveSingularForm%20ontolex%3Arepresentation%20%3FgenitiveSingular%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgrammaticalFeature%20wd%3AQ53997857%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgrammaticalFeature%20wd%3AQ146233%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgrammaticalFeature%20wd%3AQ110786%20.%0A%0A%20%20%20%20%23%20Genitive%20Plural%0A%20%20%20%20%3Flexeme%20ontolex%3AlexicalForm%20%3FgenitivePluralForm%20.%0A%20%20%20%20%3FgenitivePluralForm%20ontolex%3Arepresentation%20%3FgenitivePlural%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgrammaticalFeature%20wd%3AQ53997857%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgrammaticalFeature%20wd%3AQ146233%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgrammaticalFeature%20wd%3AQ146786%20.%0A%20%20%7D%20.%0A%0A%20%20%23%20Definite%20forms%20in%20both%20nominative%20and%20genitive.%0A%20%20OPTIONAL%20%7B%0A%20%20%20%20%23%20Nominative%20Singular%0A%20%20%20%20%3Flexeme%20ontolex%3AlexicalForm%20%3FnominativeSingularForm%20.%0A%20%20%20%20%3FnominativeSingularForm%20ontolex%3Arepresentation%20%3FQ53997851%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgrammaticalFeature%20wd%3AQ53997851%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgrammaticalFeature%20wd%3AQ131105%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgrammaticalFeature%20wd%3AQ110786%20.%0A%0A%20%20%20%20%23%20Nominative%20Plural%0A%20%20%20%20%3Flexeme%20ontolex%3AlexicalForm%20%3FnominativePluralForm%20.%0A%20%20%20%20%3FnominativePluralForm%20ontolex%3Arepresentation%20%3FnominativePlural%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgrammaticalFeature%20wd%3AQ53997851%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgrammaticalFeature%20wd%3AQ131105%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgrammaticalFeature%20wd%3AQ146786%20.%0A%0A%20%20%20%20%23%20Genitive%20Singular%0A%20%20%20%20%3Flexeme%20ontolex%3AlexicalForm%20%3FgenitiveSingularForm%20.%0A%20%20%20%20%3FgenitiveSingularForm%20ontolex%3Arepresentation%20%3FgenitiveSingular%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgrammaticalFeature%20wd%3AQ53997851%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgrammaticalFeature%20wd%3AQ146233%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgrammaticalFeature%20wd%3AQ110786%20.%0A%0A%20%20%20%20%23%20Genitive%20Plural%0A%20%20%20%20%3Flexeme%20ontolex%3AlexicalForm%20%3FgenitivePluralForm%20.%0A%20%20%20%20%3FgenitivePluralForm%20ontolex%3Arepresentation%20%3FgenitivePlural%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgrammaticalFeature%20wd%3AQ53997851%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgrammaticalFeature%20wd%3AQ146233%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgrammaticalFeature%20wd%3AQ146786%20.%0A%20%20%7D%20.%0A%0A%20%20%23%20Optional%20selection%20of%20genders.%0A%20%20OPTIONAL%20%7B%0A%20%20%20%20%3Flexeme%20wdt%3AP5185%20%3FnounGender%20.%0A%20%20%20%20FILTER%20NOT%20EXISTS%20%7B%20%3Flexeme%20wdt%3AP31%20wd%3AQ202444%20.%20%7D%0A%20%20%7D%20.%0A%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%0A%20%20%20%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%22.%0A%20%20%20%20%3FnounGender%20rdfs%3Alabel%20%3Fgender%20.%0A%20%20%7D%0A%7D%0A)
- If you go to the optional FILTER NOT EXISTS and change `lexeme` to just `l` the query will break with the result `Query timeout limit reached`
- If this broken query is passed to WikidataIntegrator then there will be no HTTP error, and the result will just hang until a keyboard interruption or other cancellation method (there will be a message printed to the terminal though: `Backing off 1.0 seconds afters 1 tries calling function with args` followed by the query)

Would it maybe be an improvement if WikidataIntegrator could handle these kinds of issues? Not sure what your thoughts are on this.

**Comment by LeMyst** [comment]
Ok, I can reproduce your issue.

To explain, because the error code 500 (query timeout by the server) is not catch by execute_sparql_query(), the method automatically fallback to backoff/wdi_backoff because of the raise_for_status(). That's why you can't catch it.

By default, wdi_backoff does an infinite amount of retries, you can change that by adding theses lines at the top of your script to change the default behaviour:
```python
from wikidataintegrator.wdi_config import config as wdi_config

wdi_config['BACKOFF_MAX_TRIES'] = 2
```

**Comment by andrewtavis** [comment]
Wonderful :) I just changed it to `wdi_config['BACKOFF_MAX_TRIES'] = 1` as that works for my purposes. 

For documentation, the import for `HTTPError` is `from requests.exceptions import HTTPError` (there are a couple libraries with `HTTPError`). This does return a 500 error code through the exception, and I've figured out how to get the rest running from there :)

Thanks so much for your help!
