### ISSUE TITLE
Does it support lexemes or lexeme validation?

### ISSUE THREAD

**Issue by dpriskorn** [SuLab/WikidataIntegrator#201]
I'm missing a section in the readme about the limitations of the software.

**Comment by andrawaag** [comment]
The RDF serialization of lexemes is different from the item data model, as such support for lexemes has yet to be implemented (i.e. WDLexemeEngine). So with WikidataIntegrator it is currently not possible to add or update entries in the Lexeme namespace. 

Having said that, the validation works on the RDF serialization, which is independent of the json object. I suspect that validation should work.
