### ISSUE TITLE
Fatameh adds P2093 statements where relevant P50 statements exist

### ISSUE THREAD

**Issue by Daniel-Mietchen** [SuLab/WikidataIntegrator#22]
e.g. https://www.wikidata.org/w/index.php?title=Q27308252&diff=506942684&oldid=496259713

**Comment by stuppie** [comment]
As in https://github.com/SuLab/WikidataIntegrator/issues/19#issuecomment-311216864,  WDI is checking for authors using ORCID IDs. These authors didn't have orcid statements. Would you suggest 
1) if an author (P50) exists with a series ordinal, but no orcid ID, automatically add the orcid ID to that item, or
2) just skip creating an author name string statement for any ordinal that exists in P50 ?

**Comment by Daniel-Mietchen** [comment]
Definitely (2) &mdash; preferably also (1) but 
- in many cases, there simply is no ORCID record for the paper, and 
- ORCID syncing is currently also done by QuickStatements Bot.
