### ISSUE TITLE
wdi_helpers.PubmedItem: Do not change existing information unless specifically prompted

### ISSUE THREAD

**Issue by Daniel-Mietchen** [SuLab/WikidataIntegrator#24]
There are several ways in which the current code 'corrects' correct statements (is there a better English expression for that? In German, we have '[verschlimmbessern](https://en.wiktionary.org/wiki/verschlimmbessern#German)', which could loosely be translated as 'correcting by making things worse'.) &mdash; one is to add a period at the end of titles/ labels (cf. #20), and there are others (e.g. #15), which should probably get separate tickets.

Here, I'd like to bring up the general issue of whether/ when the script should change existing information. My view is that this should be limited to adding missing references and updating retrieval dates. For most anything else, the default should probably be not to change anything, but to flag inconsistencies in some way that can then be worked on separately.

**Comment by stuppie** [comment]
How and where should inconsistencies be flagged? Should it be for the bot operator only in the form of warnings, logs, or errors printed? Or do you mean in a public place?

**Comment by Daniel-Mietchen** [comment]
I'm fine either way &mdash; the simplest may be a log file exposed to the bot operator, but most useful would probably be something in a public place, similar to the constraint violation reports.
