### ISSUE TITLE
wdi_helpers.PubmedItem: Do not change author name strings for no reason

### ISSUE THREAD

**Issue by Daniel-Mietchen** [SuLab/WikidataIntegrator#26]
Currently, the script often changes name strings from a format of
```
M W J Ferguson
```
to 
```
Ferguson MW
```
as in [this example](https://www.wikidata.org/w/index.php?title=Q24527236&diff=prev&oldid=512477942).

This is problematic in two ways and thus relevant for #24:
- author disambiguation is simply harder for the 'Ferguson MW' variant (i.e. with inverted first and family names and with fewer spaces)
- some information (the initial J in this case) gets lost.

**Comment by tarrow** [comment]
We should be clear that WDI isn't choosing to do it one way or another. It's simply spewing back out whatever EuropePMC has. In this case this is also how the NCBI renders the name: https://www.ncbi.nlm.nih.gov/pubmed/?term=12521975 on one page. However it is rendered `M W J Ferguson` at https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1125033/

I don't think we can work out which of the two possibilities is right with code.

There are really two options I think:
1. if an author with that series ordinal already exists then do nothing at all
2. add an additional statement and leave the old one. Both having different references. Then we can work out which is right afterwards

**Comment by stuppie** [comment]
Yes, correct. @Daniel-Mietchen WDI is not selecting or processing the name strings in any way. It is using the [API response](http://www.ebi.ac.uk/europepmc/webservices/rest/search?query=12521975&resulttype=core&format=json). The name string comes from ncbi's api the [same way](https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pubmed&id=12521975&retmode=json).
In [this example](https://www.wikidata.org/w/index.php?title=Q24527236&oldid=510443651), the name strings had no references, so don't think the default should be to not touch it. I think the appropriate thing is to replace it with a known value (from the PMC api) and give it a reference, while removing the unreferenced claim.
If they did have a reference, I think the appropriate thing to do would be # 2 for @tarrow's previous comment. Which I'll need to implement in code...

**Comment by Daniel-Mietchen** [comment]
Yes, I am aware that WDI is taking these strings straight from the API responses, and I agree that unsourced information &mdash; even if "more correct" &mdash; should in general give way to properly sourced information. So perhaps we have to think about which API calls fit best with our use cases, and whether and how to process the API responses.

For instance, [this call](https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pmc&id=PMC1125033) to NCBI's XML brings 
```
<name>
    <surname>Ferguson</surname>
    <given-names>M W J</given-names>
</name>
```

Except for the third initial J and the spaces between the initials, the surname/ given name distinction is also contained in your above-mentioned JSON responses from PMC and EuPMC, so it could be exposed on the Wikidata end.

I don't think we should go for @tarrow's option 2 anytime soon &mdash; author information is difficult enough already through the use of two properties (P50 and P2093) and an obligatory qualifier (P1545) so we should probably limit the additional variability we bring in on top of that. The current practice of allowing only one statement of either P50 or P2093 with a given P1545 seems a reasonable default to me.
