### ISSUE TITLE
Do not retry when a connection could not be established

### ISSUE THREAD

**Issue by konstin** [SuLab/WikidataIntegrator#27]
Currently, WikidataIntegrator ignores a failed attempt to establish a connection to a wikibase instance and instead retries to send the data. This should not be the default behavior.

The following exception for example shows an error in my code that was caught and hidden away internally, preventing properly handling the error in the calling code:

```
HTTPSConnectionPool(host='mediawiki.local', port=443): Max retries exceeded with url: /w/api.php?ids=Q1403&action=wbgetentities&format=json&sites=enwiki (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb2cee6da90>: Failed to establish a new connection: [Errno 111] Verbindungsaufbau abgelehnt',))
```

**Comment by stuppie** [comment]
It currently retries this because the Wikidata SPARQL endpoint has been historically unstable, and retrying often allows bot runs to continue successfully. To disable this use:

```python
from wikidataintegrator.wdi_config import config
config['BACKOFF_MAX_TRIES'] = 1

```

**Comment by konstin** [comment]
Thanks for the workaround, but I'd still argue that only Exceptions such as the one thrown by the sparql endpoint should be caught.

**Comment by stuppie** [comment]
Makes sense. Will change to only retry SPARQL queries ([execute_sparql_query](https://github.com/SuLab/WikidataIntegrator/blob/9bcadf9f7575760ea3e69b3b3de3da13e06e4594/wikidataintegrator/wdi_core.py#L1016))

**Comment by konstin** [comment]
Thanks 👍
