### ISSUE TITLE
In references, replace PubMed ID with reference URL for the respective API call?

### ISSUE THREAD

**Issue by Daniel-Mietchen** [SuLab/WikidataIntegrator#29]
WDI currently references statements as in [this example](https://www.wikidata.org/w/index.php?title=Q29618689&oldid=513396587#P1433):

> [stated in](https://www.wikidata.org/wiki/Property:P248): [Europe PubMed Central](https://www.wikidata.org/wiki/Q5412157)
> [PubMed ID](https://www.wikidata.org/wiki/Property:P698): [11972065](https://www.ncbi.nlm.nih.gov/pubmed/?term=11972065)
> [retrieved](https://www.wikidata.org/wiki/Property:P813): 4 July 2017

This is odd in a way because the PubMed ID link leads to PubMed (by way of its [formatter URL (P1630)](https://www.wikidata.org/w/index.php?title=Property:P698&oldid=511211976#P1630)), not to Europe PubMed Central. This arrangement adds complexity to verifying the statements that the references are meant to support.

An alternative way (proposed by @harej) makes use of [reference URL (P854)](https://www.wikidata.org/wiki/Property:P854) and is highlighted in [this example](https://www.wikidata.org/w/index.php?title=Q29618689&oldid=511904940#P1433) 
> [stated in](https://www.wikidata.org/wiki/Property:P248): [PubMed](https://www.wikidata.org/wiki/Q180686)
> [reference URL](https://www.wikidata.org/wiki/Property:P854): [https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pubmed&retmode=json&id=11972065](https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pubmed&retmode=json&id=11972065)
> [retrieved](https://www.wikidata.org/wiki/Property:P813): 4 July 2017

This facilitates verification &mdash; and even automated approaches to it &mdash; but at the cost (which some may perceive as too high) of having to navigate those API responses rather than something human-readable.

**Comment by stuppie** [comment]
@Daniel-Mietchen Yes, this is a good point. I have talked with @harej (James Hare) about this. More specifically, he is planning on merging his [BiblioWikidata library](https://github.com/harej/BiblioWikidata), which currently uses http://doi.or and the eutils API, into the Reference creator, and then changing the references to point to the source and API call url. I was planning on holding off changing the reference format until this is done.

**Comment by stuppie** [comment]
Ok, so I don't think this merge is happening anytime soon, so I went ahead and changed the reference so that if an item has a PMCID, it uses that in the reference, so you can click the ID and it takes you right to that page. 
https://www.wikidata.org/wiki/Q29618689#P356
If an item does not have a PMCID, it will still use the Pubmed ID in the reference. Yes, this is not ideal, but is a workaround until someone implements PubmedItem using other APIs..
I'm mostly against using the reference URLs, (if we can avoid it) because if (when!) the API or url changes, than all of a sudden all of the references are broken.

**Comment by stuppie** [comment]
It will add the reference URL to all new references now. 
https://github.com/SuLab/WikidataIntegrator/commit/046ce33f33c505110bfd8dddb6edb461078cd21f
