### ISSUE TITLE
Handle wdi_core.WDItemEngine.get_wd_entity failure

### ISSUE THREAD

**Issue by stuppie** [SuLab/WikidataIntegrator#3]
Occasionally this temporarily, randomly fails
https://github.com/sebotic/WikidataIntegrator/blob/master/wikidataintegrator/wdi_core.py#L218
Except JSONDecodeError? Retry?

```
  File "/var/lib/jenkins/workspace/interpro/venv/local/lib/python3.5/site-packages/wikidataintegrator-0.0.318-py3.5.egg/wikidataintegrator/wdi_core.py", line 174, in __init__
  File "/var/lib/jenkins/workspace/interpro/venv/local/lib/python3.5/site-packages/wikidataintegrator-0.0.318-py3.5.egg/wikidataintegrator/wdi_core.py", line 183, in init_data_load
  File "/var/lib/jenkins/workspace/interpro/venv/local/lib/python3.5/site-packages/wikidataintegrator-0.0.318-py3.5.egg/wikidataintegrator/wdi_core.py", line 235, in get_wd_entity
  File "/var/lib/jenkins/workspace/interpro/venv/local/lib/python3.5/site-packages/requests/models.py", line 826, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by stuppie** [comment]
Maybe GET requests on the wdapi should use this?
https://pypi.python.org/pypi/retrying

**Comment by sebotic** [comment]
In what context is it failing? only on jenkins? Never had that before. Did you check the HTTP error codes? Because usually, when the json cannot be parsed it is due to the server returning an error or an incomplete json.

I'd say that the rety package should only be used if the error cannot be solved otherwise.

**Comment by stuppie** [comment]
Fails once every like.... couple thousand items. If I run the same thing again it works fine, so its that the server is returning a corrupt (or blank) response. Don't know the error code cause I can't replicate it.

**Comment by sebotic** [comment]
ok, if there are issues with the Wikidata API, we usually just skip that one, and handle it at the next bot run. But if a retry within a few seconds works, that should be a good workaround.

**Comment by sebotic** [comment]
just another thing to consider: Are requests and urllib3 up-to-date?

**Comment by stuppie** [comment]
In jenkins it is downloading everything fresh every time. New virtualenv and pip installing all requirements. Its using requests 2.12.1 which is the latest version and Python 3.5.1

**Comment by stuppie** [comment]
@sebotic If this line throws a HTTPError, which is then caught and logged, self.wd_json_representation will get set to None ([link](https://github.com/sebotic/WikidataIntegrator/blob/master/wikidataintegrator/wdi_core.py#L183)). Won't this cause additional problems? For example, ([here](https://github.com/sebotic/WikidataIntegrator/blob/master/wikidataintegrator/wdi_core.py#L558))

**Comment by stuppie** [comment]
See 6f622a7b8ef6ced2197b95efb1ecbe6c449cb48a

**Comment by sebotic** [comment]
looks like this is not available as a dedicated package?

**Comment by stuppie** [comment]
Hm, no its not on pip. The one I looked at before [retrying](https://github.com/rholder/retrying) had been inactive for a while, while [backoff](https://github.com/litl/backoff/) hadn't, which is why I went with it. I now see [tenacity](https://github.com/jd/tenacity), which is a fork of retrying, which is active. All three seem to do basically the exact same thing though...
