### ISSUE TITLE
For paper items, add descriptions in other languages

### ISSUE THREAD

**Issue by Daniel-Mietchen** [SuLab/WikidataIntegrator#30]
this would probably be the simplest approach given the discussion at https://www.wikidata.org/w/index.php?title=Wikidata:Project_chat&oldid=528577863#A_Big_Task:_Adding_language_descriptions_to_scientific_article_items .

**Comment by stuppie** [comment]
Looks like there is a bot doing this:
https://www.wikidata.org/w/index.php?title=Q42758027&curid=44013942&diff=589843599&oldid=589835166
