### ISSUE TITLE
Improve duplicate detection

### ISSUE THREAD

**Issue by Daniel-Mietchen** [SuLab/WikidataIntegrator#31]
My bot has used Fatameh to create
https://www.wikidata.org/w/index.php?title=Q33882145&oldid=528418344 
( DOI: 10.1038/NCOMMS15932 ; PMCID: 5500850 ; PubMed ID: 28671182 )
but there had already been 
https://www.wikidata.org/wiki/Q31724476 
( DOI: 10.1038/NCOMMS15932 ; PMCID: 5500850 ; PubMed ID: 28671182 ).
How could the duplication checks have missed that?

**Comment by Daniel-Mietchen** [comment]
Digging in a little further, the state of Q31724476 at the time of creation of Q33882145
was just [this](https://www.wikidata.org/w/index.php?title=Q31724476&oldid=512569197), i.e. 
( DOI: 10.1038/NCOMMS15932 ; unreferenced ). Still, I think it should have been detected and the item updated rather than created anew.

Possibly relevant to #24.

**Comment by stuppie** [comment]
I added the DOI prop to the core IDs: https://github.com/SuLab/WikidataIntegrator/commit/b5e7964f242a7e3dc12650e98ed3c51aca383ba0
Also, keep in mind, that you can add any property you want to the core IDs within a script by doing, for example:
```python
from wikidataintegrator.wdi_property_store import wd_properties
wd_properties['P356'] = {'core_id': True, 'datatype': 'string', 'domain': ['scientific_article'], 'name': 'DOI'}
```
