### ISSUE TITLE
Add full support for DOIs

### ISSUE THREAD

**Issue by Daniel-Mietchen** [SuLab/WikidataIntegrator#32]
At the moment, DOIs are added to items that have been started by way of a PMID or a PMCID, but 
- items cannot be started by way of a DOI, and 
- #31 suggests that duplicate detection for DOIs does not work properly.

**Comment by stuppie** [comment]
Items can be started using the DOI:

```python
from wikidataintegrator.wdi_login import WDLogin
from wikidataintegrator.wdi_helpers import PubmedItem
login = WDLogin(USER, PASS)
p = PubmedItem("10.1038/nature23282", "DOI")
p.get_or_create(login)
```
See: https://www.wikidata.org/wiki/Q34224902

**Comment by nichtich** [comment]
This only supports DOIs found in PubMed. See https://github.com/SuLab/WikidataIntegrator/issues/52 for an issue to support all kinds of DOIs via CrossRef.
