### ISSUE TITLE
Support maxlag

### ISSUE THREAD

**Issue by tarrow** [SuLab/WikidataIntegrator#34]
We should support the maxlag parameter when doing API calls so that users can easily follow the API etiquette guidelines.

https://www.mediawiki.org/wiki/Manual:Maxlag_parameter

The option then is to either retry or to just let the user know. I think we should just let the user know and they can decide when to retry.

**Comment by framawiki** [comment]
Please have a look on https://phabricator.wikimedia.org/T173921 and https://www.wikidata.org/wiki/Wikidata:Administrators%27_noticeboard#Maxlag_parameter_not_respected too.

**Comment by sebotic** [comment]
we should be able to implement it, so far, it has not really been necessary, at least not for our bots, as Wikidata has a specific error message where it goes into read-only mode, for e.g. 60 sec. when the slave databases lag behind.

**Comment by sebotic** [comment]
I implemented maxlag now, default is at 5 sec, can be set in wdi_config.py for now

**Comment by stuppie** [comment]
https://github.com/SuLab/WikidataIntegrator/commit/379f4ceba11a644c7e483c4db3ddb2b90e88b571
