### ISSUE TITLE
Redefine "good references"

### ISSUE THREAD

**Issue by stuppie** [SuLab/WikidataIntegrator#35]
WDI is often failing now because the "good ref" system is generating a list of pmids, which now numbers in the millions, and so the queries often time out. 
This https://github.com/SuLab/WikidataIntegrator/commit/d3c4da01743bda94da701cdc48978c2704269ff4 was implemented as a workaround, but still often times out.

I propose the default "good reference" to be changed to be defined as:
Any reference that is not empty, or only includes "imported from" and/or a retrieved date.

**Comment by stuppie** [comment]
See: https://github.com/SuLab/WikidataIntegrator/commit/ca9f1cada21876f73ad10fe9a44c45039c7aa9d9

**Comment by sebotic** [comment]
the timeout issue has been solved by not checking anymore if the PMID is a Wikidata publication item. 

For a good reference, the minimum requirement should be a 'stated in' statement, but what we actually want is a 'stated in' + a database id + a date. Keeping that as a good ref requirement should allow to enforce that, at least to some degree.
