### ISSUE TITLE
log file not writing

### ISSUE THREAD

**Issue by skeating** [SuLab/WikidataIntegrator#46]
Hi Guys

I have this code:

            try:
                item_id_value = wdpage.write(self.logincreds)

                if item_id_value != 0:
                    if item_id_value not in global_variables.edited_wd_pages:
                        global_variables.edited_wd_pages.append(item_id_value)
                    print('https://www.wikidata.org/wiki/{0}'.format(item_id_value))
            except Exception as e:
                wdi_core.WDItemEngine.log("ERROR",
                                          wdi_helpers.format_msg(result['pwId']['value'], 'P3937', None, str(e), type(e)))
                global_variables.exceptions.append(e.args[0]['error']['info'])

This does indeed catch the exception that there is already an existing item with a given label

Stepping through the code it appears to create a file WD_bot_run-20180227_10:21.log and it certainly writes to the stream associated with that file but what I get is a file named WD_bot_run-20180227_10 which is empty.

Note P3937 is Reactome ID and the value is the Reactome ID for the page being added.

Using Python 34 64 bits on Windows 8.1.

Any thoughts ...

Not a major issue as you can see I am capturing the exception and reporting it myself but thought I would let you know.

Sarah

**Comment by stuppie** [comment]
Hm, not sure. I just tried the following code by itself and the log file gets written just fine.

```
from wikidataintegrator import wdi_core
wdi_core.WDItemEngine.log("ERROR", "sdf")
```

Are you running a custom setup_logging call anywhere? Can you try the above code by itself and see if that works?

FYI: We have a helper function `wdi_helpers.try_write`, which does what your code does above. (try write, catch exception, log a create, update, or skip, and returns whether or not the write was successful)

**Comment by stuppie** [comment]
Apparently you can't have colons in Windows file names... Did not know that...
Run setup_logging beforehand and manually set the log_name
For example:

```
from wikidataintegrator import wdi_core
import time
wdi_core.WDItemEngine.setup_logging(log_name="WD_bot_run-{}.log".format(time.strftime('%Y%m%d_%H_%M', time.localtime())))
wdi_core.WDItemEngine.log("ERROR", "sd")
```

**Comment by skeating** [comment]
Indeed setting the filename to not use a colon worked.

Thank you
