### ISSUE TITLE
Translated titles from PubMed are enclosed in brackets

### ISSUE THREAD

**Issue by moqri** [SuLab/WikidataIntegrator#49]
Example: https://www.wikidata.org/wiki/Q50804562

As requested here, the titles should not be enclosed in brackets: https://www.wikidata.org/wiki/Wikidata:Requests_for_permissions/Bot/maria_research_bot

**Comment by nichtich** [comment]
The brackets indicate the article is not in English so this is not the original title. At least the article language should be preserved with https://www.wikidata.org/wiki/Property:P364, otherwise it looks like the article is English
