### ISSUE TITLE
wdi_helpers.CrossRefItem: create method to fetch data via DOI from CrossRef

### ISSUE THREAD

**Issue by nichtich** [SuLab/WikidataIntegrator#52]
`wdi_helpers.PubmedItem` fetches publication data from https://www.ebi.ac.uk/ so apparently only publications with PubMed-ID can be imported. To support importing publications with DOI, data has to be taken from CrossRef API, e.g. with a new method `wdi_helpers.CrossRefItem`. There is [a Python library](https://github.com/sckott/habanero) to do so. The format is [documented here](https://github.com/Crossref/rest-api-doc/blob/master/api_format.md).

**Comment by Samwalton9** [comment]
I'm seeing a bunch of references to the crossref API and DOIs in the code now, is this fixed? @stuppie

**Comment by stuppie** [comment]
Yes, crossref API is supported
https://github.com/SuLab/WikidataIntegrator/blob/842ddb599cbced15609ea7905da015b0f3956c21/wikidataintegrator/wdi_helpers/publication.py#L438
