### ISSUE TITLE
Issue with WDItemEngine

### ISSUE THREAD

**Issue by moqri** [SuLab/WikidataIntegrator#53]
The below code (adopted from your example) returns the correct result:

item = wdi_core.WDString(value='1', prop_nr='P351')
wd_item = wdi_core.WDItemEngine(item_name='A1BG', domain='gene', data=[item],search_only=True)
print wd_item.entity_metadata

But the below code for the same item returns an empty result!

item = wdi_core.WDString(value='ENSG00000121410', prop_nr='P594')
wd_item = wdi_core.WDItemEngine(item_name='A1BG', domain='gene', data=[item],search_only=True)
print wd_item.entity_metadata

**Comment by stuppie** [comment]
Yes, this is expected because P594 is not set as a core_id by default (as in, its not used for searching for items). You can set it as a core id for yourself by doing:

> from wikidataintegrator import wdi_property_store
> wdi_property_store.wd_properties['P594']['core_id'] = True

and then you're example code will work.

**Comment by moqri** [comment]
Thanks, that does the job!
