### ISSUE TITLE
Python2 compatibility

### ISSUE THREAD

**Issue by stuppie** [SuLab/WikidataIntegrator#64]
I broke python2 compatibility with [this](https://github.com/SuLab/WikidataIntegrator/commit/5214b87c3bf8a100f3d60d2295e16bca2d6707aa) commit. (Apparently python2 doesn't have lru_cache). Unless someone strongly objects, I plan on not fixing this, as it is 2018 and nobody should be using python2 anymore.

**Comment by sebotic** [comment]
Well, looking at most large libraries like numpy, pandas, tensorflow, these all have py2.7 compatibility. So I'd assume many people still cling to py2.7 as they have a ton of code they need/want to keep compatibility to.

**Comment by stuppie** [comment]
Many large libraries (pandas and numpy included) have pledged to stop Py2 development by Jan 2019 !
http://python3statement.org/

**Comment by andrawaag** [comment]
With WD 0.2.0 WDI requires python 3.6>. Removed the qualifier about Python 2.7 from setup.py
