### ISSUE TITLE
When testing correct installation wikidataintegrator won´t retrieve anything.

### ISSUE THREAD

**Issue by WalterKlosse** [SuLab/WikidataIntegrator#78]

**Comment by stuppie** [comment]
Hello @WalterKlosse ,
If you could detail the issue using the template below, that would be very helpful.... Thanks

#### Issue description



#### Steps to reproduce the issue

1.  
2. 
3. 


#### What's the expected result?

-


#### What's the actual result?

-

#### Operating system, environment, python version, wikidataintegrator version, etc..

- 

#### Additional details / screenshot / actual code

- ![Screenshot]()

**Comment by stuppie** [comment]
Closed due to no response
