### ISSUE TITLE
Add new Property functionality

### ISSUE THREAD

**Issue by tarrow** [SuLab/WikidataIntegrator#80]
It would be awesome if we could use WDI to make new properties as well as items (on Wikibases that are not wikidata.org)

**Comment by stuppie** [comment]
You can! See example [here](https://github.com/stuppie/wikibase-tools/blob/b0ba76f33f80c12da9ce51a1d2bcadbb4899033a/wikibase_tools/make_entities.py#L96).
lmk if that works for you .. --Greg
