### ISSUE TITLE
Issues with fastrun

### ISSUE THREAD

**Issue by stuppie** [SuLab/WikidataIntegrator#84]
Fastrun on [obographs_DO.py](https://github.com/SuLab/scheduled-bots/blob/master/scheduled_bots/ontology/obographs_DO.py) is not very fast anymore. I ran it through Pycharm's profiler, and I think it has to do with [__select_wd_item](https://github.com/SuLab/WikidataIntegrator/blob/842ddb599cbced15609ea7905da015b0f3956c21/wikidataintegrator/wdi_core.py#L387). Specifically this line https://github.com/SuLab/WikidataIntegrator/blob/842ddb599cbced15609ea7905da015b0f3956c21/wikidataintegrator/wdi_core.py#L423

**Comment by andrawaag** [comment]
moved to: https://github.com/SuLab/scheduled-bots/issues/26
