### ISSUE TITLE
Upgrade jenkins bots to Python 3.6 to allow ShEx support in our bots.

### ISSUE THREAD

**Issue by andrawaag** [SuLab/WikidataIntegrator#85]
I have implemented a ShEx helper function in the Wikidata Integrator. However, the pyShex library requires python 3.6. 
Currently, the helper function is implemented in the ShEx branch of the WDI GitHub repository. 

Before merging the ShEx branch into the master branch:
[] change this line in jenkins "virtualenv -p python35 venv" to "virtualenv -p python36 venv"
[] anything else?

**Comment by andrawaag** [comment]
With release of version 0.2.0 this is fixed

**Comment by andrewsu** [comment]
addressed in https://github.com/SuLab/WikidataIntegrator/commit/4c8c294bd0285f8ac25e0cd1491e32699ffab6ea
