### ISSUE TITLE
Review redundant dependencies in both setup.py and requirements.txt

### ISSUE THREAD

**Issue by andrawaag** [SuLab/WikidataIntegrator#88]
Currently, WDI dependencies are set in both requirements.txt and setup.py. Some of the dependencies currently set in requirements.txt need to be set in setup.py. Moving these to setup.py however, stalled the deployment to Pypi, with the direct effect of all bots being stalled. To get the bots going, I added some of the dependencies in both setup.py and requirements.txt, to have the bots running again. 

Once all bots are stable, this issue needs to be revisited to get rid of the current redundancies.

**Comment by stuppie** [comment]
Ya, this was weird, I'm not sure why this happens, but if you have pandas in the setup.py, it fails to install. Its a known issue: https://github.com/numpy/numpy/issues/2434

**Comment by andrawaag** [comment]
The problem seems to originate in the order where requirements and setup.py are called. See: https://github.com/hsolbrig/PyShEx/issues/39#issuecomment-466807148 for details. 
An quick sollution is to first call pip requirements and then run setup.py. Using [Pipenv](https://pipenv.readthedocs.io/en/latest/) is suggested as a better solution. We need to investigate and maybe try running one bot with pipenv

**Comment by andrawaag** [comment]
Pipenv indeed fixes this issue. For now I am leaving this issue open, until pipenv is deployed in all running bots
