### ISSUE TITLE
Multiple licenses expressed in the code

### ISSUE THREAD

**Issue by andrawaag** [SuLab/WikidataIntegrator#90]
The main license is [MIT](https://github.com/SuLab/WikidataIntegrator/blob/master/LICENSE.txt) yet 
on [wdi-core](https://github.com/SuLab/WikidataIntegrator/blob/master/wikidataintegrator/wdi_core.py) the license is expressed as GPL

> ProteinBoxBot is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with ProteinBoxBot.  If not, see <http://www.gnu.org/licenses/>.

I assume we need to either delete the latter or replace it with the MIT license text. If we replace it with MIT should we add MIT license headers on all our python scripts, including the different bots?

**Comment by andrewsu** [comment]
I'd support removing that GPL blurb.  any objection @stuppie @sebotic ?  

(If adding headers on each file is standard, sounds good to me.  Otherwise, seems reasonable to me that the license file at the root governs the whole repo.)
