### ISSUE TITLE
[Wikidata] [Breaking change] Important for Wikidata tools maintainers: wb_terms table to be dropped

### ISSUE THREAD

**Issue by andrewsu** [SuLab/WikidataIntegrator#93]
announcement: https://lists.wikimedia.org/pipermail/wikidata-tech/2019-April/001395.html

does this affect WDI?

> Hello all,
> 
> This is an important announcement for all the tool builders and maintainers
> who access Wikidata’s data by *querying directly Labs database replicas*.
> 
> In May-June 2019, the Wikidata development team will drop the wb_terms
> table from the database in favor of a new optimized schema. Over years,
> this table has become too big, causing various issues.
> 
> This change requires the tools using wb_terms to be updated. Developers and
> maintainers will need to *adapt their code* to the new schema before the
> migration starts and switch to the new code when the migration starts.
> 
> The migration will start on *May 29th*. On May 15th, a test system will be
> available for you to test your code.
> 
> The table being used by plenty of external tools, we are setting up a
> process to make sure that the change can be done together with the
> developers and maintainers, without causing issues and broken tools. Most
> of the documentation and updates will take place on Phabricator:
> 
>    - In this Phabricator task <https://phabricator.wikimedia.org/T221764>,
>    you can find a description of the changes and the process, and you can ask
>    for more details or for help in the comments. This is also where updates
>    will be announced if necessary.
>    - On the Tool Builders Migration board
>    <https://phabricator.wikimedia.org/tag/wb_terms_-_tool_builders_migration>
>    you will find all the details about the migration, how to update your
>    tool <https://phabricator.wikimedia.org/T221765>, and you can add your
>    own tasks.
>    - If you need to discuss with the Wikidata developers or get more
>    specific help, we set up two dedicated IRC meetings and a session at the
>    Wikimedia hackathon. More information in this task
>    <https://phabricator.wikimedia.org/T221764>.
> 
> We are aware that this change will ask you to make some important changes
> in your code, and we are willing to help you as much as our resources allow
> us to. We hope that you will understand that this change is made to avoid
> bigger issues in the near future.
> 
> Note that this change is not impacting Wikibase instances outside of
> Wikidata. A dedicated migration plan and announcement will follow.
> 
> We strongly encourage you to not wait until last minute to make the changes
> in your code. If you have any question or issue, we will be happy to help.
> In order to keep the discussions in one place, please ask questions or
> raise issues directly in the Phabricator task and board.
> 
> Thanks for your understanding,
> Cheers,
> -- 
> Léa Lacroix
> Project Manager Community Communication for Wikidata
> 
> Wikimedia Deutschland e.V.
> Tempelhofer Ufer 23-24
> 10963 Berlin
> www.wikimedia.de
> 
> Wikimedia Deutschland - Gesellschaft zur Förderung Freien Wissens e. V.
> 
> Eingetragen im Vereinsregister des Amtsgerichts Berlin-Charlottenburg unter
> der Nummer 23855 Nz. Als gemeinnützig anerkannt durch das Finanzamt für
> Körperschaften I Berlin, Steuernummer 27/029/42207.

**Comment by tarrow** [comment]
As far as I knew WDI doesn't ever access the DB directly but instead always
uses the http apis. In this case there should be no impact at all

**Comment by andrawaag** [comment]
Indeed none of the bots seems affected so far
